//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZwillingCevaWebService.AIFCargoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AIFCargoService.AIFCargoWebServicesSoap")]
    public interface AIFCargoWebServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOrderToUPS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZwillingCevaWebService.AIFCargoService.UPSOrderResponse[] SendOrderToUPS(ZwillingCevaWebService.AIFCargoService.UPSLogin login, ZwillingCevaWebService.AIFCargoService.UPSSendOrderRequest[] UpsData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOrderToUPS", ReplyAction="*")]
        System.Threading.Tasks.Task<ZwillingCevaWebService.AIFCargoService.UPSOrderResponse[]> SendOrderToUPSAsync(ZwillingCevaWebService.AIFCargoService.UPSLogin login, ZwillingCevaWebService.AIFCargoService.UPSSendOrderRequest[] UpsData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelOrderToUPS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZwillingCevaWebService.AIFCargoService.UPSCancelOrderResponse CancelOrderToUPS(ZwillingCevaWebService.AIFCargoService.UPSLogin login, ZwillingCevaWebService.AIFCargoService.UPSCancelOrder cancelOrderData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelOrderToUPS", ReplyAction="*")]
        System.Threading.Tasks.Task<ZwillingCevaWebService.AIFCargoService.UPSCancelOrderResponse> CancelOrderToUPSAsync(ZwillingCevaWebService.AIFCargoService.UPSLogin login, ZwillingCevaWebService.AIFCargoService.UPSCancelOrder cancelOrderData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOrderToYK", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZwillingCevaWebService.AIFCargoService.YKOrderResponse[] SendOrderToYK(ZwillingCevaWebService.AIFCargoService.YKLogin login, ZwillingCevaWebService.AIFCargoService.YKSendOrderRequest[] ykData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOrderToYK", ReplyAction="*")]
        System.Threading.Tasks.Task<ZwillingCevaWebService.AIFCargoService.YKOrderResponse[]> SendOrderToYKAsync(ZwillingCevaWebService.AIFCargoService.YKLogin login, ZwillingCevaWebService.AIFCargoService.YKSendOrderRequest[] ykData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelOrderToYK", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZwillingCevaWebService.AIFCargoService.YKCancelOrderResponse[] CancelOrderToYK(ZwillingCevaWebService.AIFCargoService.YKLogin login, ZwillingCevaWebService.AIFCargoService.YKCancelOrderRequest[] ykData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelOrderToYK", ReplyAction="*")]
        System.Threading.Tasks.Task<ZwillingCevaWebService.AIFCargoService.YKCancelOrderResponse[]> CancelOrderToYKAsync(ZwillingCevaWebService.AIFCargoService.YKLogin login, ZwillingCevaWebService.AIFCargoService.YKCancelOrderRequest[] ykData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreatePDF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZwillingCevaWebService.AIFCargoService.Crystal CreatePDF(string docEntry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreatePDF", ReplyAction="*")]
        System.Threading.Tasks.Task<ZwillingCevaWebService.AIFCargoService.Crystal> CreatePDFAsync(string docEntry);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UPSLogin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string musteriKoduField;
        
        private string kullaniciKoduField;
        
        private string sifreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MusteriKodu {
            get {
                return this.musteriKoduField;
            }
            set {
                this.musteriKoduField = value;
                this.RaisePropertyChanged("MusteriKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string KullaniciKodu {
            get {
                return this.kullaniciKoduField;
            }
            set {
                this.kullaniciKoduField = value;
                this.RaisePropertyChanged("KullaniciKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Sifre {
            get {
                return this.sifreField;
            }
            set {
                this.sifreField = value;
                this.RaisePropertyChanged("Sifre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Crystal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int valField;
        
        private string descField;
        
        private string pathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Val {
            get {
                return this.valField;
            }
            set {
                this.valField = value;
                this.RaisePropertyChanged("Val");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("Desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
                this.RaisePropertyChanged("Path");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cargoKeyField;
        
        private int errCodeField;
        
        private string errDescField;
        
        private string invoiceKeyField;
        
        private long docIdField;
        
        private long operationCodeField;
        
        private string operationStatusField;
        
        private string operationMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CargoKey {
            get {
                return this.cargoKeyField;
            }
            set {
                this.cargoKeyField = value;
                this.RaisePropertyChanged("CargoKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ErrCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
                this.RaisePropertyChanged("ErrCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
                this.RaisePropertyChanged("ErrDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string invoiceKey {
            get {
                return this.invoiceKeyField;
            }
            set {
                this.invoiceKeyField = value;
                this.RaisePropertyChanged("invoiceKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long docId {
            get {
                return this.docIdField;
            }
            set {
                this.docIdField = value;
                this.RaisePropertyChanged("docId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long operationCode {
            get {
                return this.operationCodeField;
            }
            set {
                this.operationCodeField = value;
                this.RaisePropertyChanged("operationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string operationStatus {
            get {
                return this.operationStatusField;
            }
            set {
                this.operationStatusField = value;
                this.RaisePropertyChanged("operationStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string operationMessage {
            get {
                return this.operationMessageField;
            }
            set {
                this.operationMessageField = value;
                this.RaisePropertyChanged("operationMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class YKCancelOrderResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string outResultField;
        
        private string outFlagField;
        
        private long jobIdField;
        
        private long countField;
        
        private string errCodeField;
        
        private CancelDetails detailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OutResult {
            get {
                return this.outResultField;
            }
            set {
                this.outResultField = value;
                this.RaisePropertyChanged("OutResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OutFlag {
            get {
                return this.outFlagField;
            }
            set {
                this.outFlagField = value;
                this.RaisePropertyChanged("OutFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long jobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
                this.RaisePropertyChanged("jobId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
                this.RaisePropertyChanged("errCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public CancelDetails Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
                this.RaisePropertyChanged("Details");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class YKCancelOrderRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cargoKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CargoKey {
            get {
                return this.cargoKeyField;
            }
            set {
                this.cargoKeyField = value;
                this.RaisePropertyChanged("CargoKey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Details : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cargoKeyField;
        
        private int errCodeField;
        
        private string errDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CargoKey {
            get {
                return this.cargoKeyField;
            }
            set {
                this.cargoKeyField = value;
                this.RaisePropertyChanged("CargoKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ErrCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
                this.RaisePropertyChanged("ErrCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
                this.RaisePropertyChanged("ErrDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class YKOrderResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string outResultField;
        
        private string outFlagField;
        
        private long jobIdField;
        
        private long countField;
        
        private string errCodeField;
        
        private Details detailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OutResult {
            get {
                return this.outResultField;
            }
            set {
                this.outResultField = value;
                this.RaisePropertyChanged("OutResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OutFlag {
            get {
                return this.outFlagField;
            }
            set {
                this.outFlagField = value;
                this.RaisePropertyChanged("OutFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long jobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
                this.RaisePropertyChanged("jobId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
                this.RaisePropertyChanged("errCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Details Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
                this.RaisePropertyChanged("Details");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class YKSendOrderRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cargoKeyField;
        
        private string invoiceKeyField;
        
        private string receiverCustNameField;
        
        private string receiverAddressField;
        
        private string cityNameField;
        
        private string townNameField;
        
        private string receiverPhone1Field;
        
        private string receiverPhone2Field;
        
        private string receiverPhone3Field;
        
        private string emailAddressField;
        
        private long taxOfficeIdField;
        
        private string taxNumberField;
        
        private string taxOfficeNameField;
        
        private double desiField;
        
        private bool desiFieldSpecified;
        
        private double kgField;
        
        private bool kgFieldSpecified;
        
        private int cargoCountField;
        
        private string waybillNoField;
        
        private string specialField1Field;
        
        private string specialField2Field;
        
        private string specialField3Field;
        
        private double ttInvoiceAmountField;
        
        private bool ttInvoiceAmountFieldSpecified;
        
        private long ttDocumentIdField;
        
        private string ttCollectionTypeField;
        
        private string ttDocumentSaveTypeField;
        
        private long dcSelectedCreditField;
        
        private long dcCreditRuleField;
        
        private string descriptionField;
        
        private string orgGeoCodeField;
        
        private string privilegeOrderField;
        
        private string custProdIdField;
        
        private string orgReceiverCustIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cargoKey {
            get {
                return this.cargoKeyField;
            }
            set {
                this.cargoKeyField = value;
                this.RaisePropertyChanged("cargoKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string invoiceKey {
            get {
                return this.invoiceKeyField;
            }
            set {
                this.invoiceKeyField = value;
                this.RaisePropertyChanged("invoiceKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string receiverCustName {
            get {
                return this.receiverCustNameField;
            }
            set {
                this.receiverCustNameField = value;
                this.RaisePropertyChanged("receiverCustName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string receiverAddress {
            get {
                return this.receiverAddressField;
            }
            set {
                this.receiverAddressField = value;
                this.RaisePropertyChanged("receiverAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
                this.RaisePropertyChanged("cityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string townName {
            get {
                return this.townNameField;
            }
            set {
                this.townNameField = value;
                this.RaisePropertyChanged("townName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string receiverPhone1 {
            get {
                return this.receiverPhone1Field;
            }
            set {
                this.receiverPhone1Field = value;
                this.RaisePropertyChanged("receiverPhone1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string receiverPhone2 {
            get {
                return this.receiverPhone2Field;
            }
            set {
                this.receiverPhone2Field = value;
                this.RaisePropertyChanged("receiverPhone2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string receiverPhone3 {
            get {
                return this.receiverPhone3Field;
            }
            set {
                this.receiverPhone3Field = value;
                this.RaisePropertyChanged("receiverPhone3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("emailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public long taxOfficeId {
            get {
                return this.taxOfficeIdField;
            }
            set {
                this.taxOfficeIdField = value;
                this.RaisePropertyChanged("taxOfficeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string taxNumber {
            get {
                return this.taxNumberField;
            }
            set {
                this.taxNumberField = value;
                this.RaisePropertyChanged("taxNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string taxOfficeName {
            get {
                return this.taxOfficeNameField;
            }
            set {
                this.taxOfficeNameField = value;
                this.RaisePropertyChanged("taxOfficeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public double desi {
            get {
                return this.desiField;
            }
            set {
                this.desiField = value;
                this.RaisePropertyChanged("desi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool desiSpecified {
            get {
                return this.desiFieldSpecified;
            }
            set {
                this.desiFieldSpecified = value;
                this.RaisePropertyChanged("desiSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public double kg {
            get {
                return this.kgField;
            }
            set {
                this.kgField = value;
                this.RaisePropertyChanged("kg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool kgSpecified {
            get {
                return this.kgFieldSpecified;
            }
            set {
                this.kgFieldSpecified = value;
                this.RaisePropertyChanged("kgSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public int cargoCount {
            get {
                return this.cargoCountField;
            }
            set {
                this.cargoCountField = value;
                this.RaisePropertyChanged("cargoCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string waybillNo {
            get {
                return this.waybillNoField;
            }
            set {
                this.waybillNoField = value;
                this.RaisePropertyChanged("waybillNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string specialField1 {
            get {
                return this.specialField1Field;
            }
            set {
                this.specialField1Field = value;
                this.RaisePropertyChanged("specialField1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string specialField2 {
            get {
                return this.specialField2Field;
            }
            set {
                this.specialField2Field = value;
                this.RaisePropertyChanged("specialField2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string specialField3 {
            get {
                return this.specialField3Field;
            }
            set {
                this.specialField3Field = value;
                this.RaisePropertyChanged("specialField3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public double ttInvoiceAmount {
            get {
                return this.ttInvoiceAmountField;
            }
            set {
                this.ttInvoiceAmountField = value;
                this.RaisePropertyChanged("ttInvoiceAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ttInvoiceAmountSpecified {
            get {
                return this.ttInvoiceAmountFieldSpecified;
            }
            set {
                this.ttInvoiceAmountFieldSpecified = value;
                this.RaisePropertyChanged("ttInvoiceAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public long ttDocumentId {
            get {
                return this.ttDocumentIdField;
            }
            set {
                this.ttDocumentIdField = value;
                this.RaisePropertyChanged("ttDocumentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string ttCollectionType {
            get {
                return this.ttCollectionTypeField;
            }
            set {
                this.ttCollectionTypeField = value;
                this.RaisePropertyChanged("ttCollectionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string ttDocumentSaveType {
            get {
                return this.ttDocumentSaveTypeField;
            }
            set {
                this.ttDocumentSaveTypeField = value;
                this.RaisePropertyChanged("ttDocumentSaveType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public long dcSelectedCredit {
            get {
                return this.dcSelectedCreditField;
            }
            set {
                this.dcSelectedCreditField = value;
                this.RaisePropertyChanged("dcSelectedCredit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public long dcCreditRule {
            get {
                return this.dcCreditRuleField;
            }
            set {
                this.dcCreditRuleField = value;
                this.RaisePropertyChanged("dcCreditRule");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string orgGeoCode {
            get {
                return this.orgGeoCodeField;
            }
            set {
                this.orgGeoCodeField = value;
                this.RaisePropertyChanged("orgGeoCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string privilegeOrder {
            get {
                return this.privilegeOrderField;
            }
            set {
                this.privilegeOrderField = value;
                this.RaisePropertyChanged("privilegeOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string custProdId {
            get {
                return this.custProdIdField;
            }
            set {
                this.custProdIdField = value;
                this.RaisePropertyChanged("custProdId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string orgReceiverCustId {
            get {
                return this.orgReceiverCustIdField;
            }
            set {
                this.orgReceiverCustIdField = value;
                this.RaisePropertyChanged("orgReceiverCustId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class YKLogin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userLanguageField;
        
        private string wsPasswordField;
        
        private string wsUserNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userLanguage {
            get {
                return this.userLanguageField;
            }
            set {
                this.userLanguageField = value;
                this.RaisePropertyChanged("userLanguage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string wsPassword {
            get {
                return this.wsPasswordField;
            }
            set {
                this.wsPasswordField = value;
                this.RaisePropertyChanged("wsPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string wsUserName {
            get {
                return this.wsUserNameField;
            }
            set {
                this.wsUserNameField = value;
                this.RaisePropertyChanged("wsUserName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UPSCancelOrderResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private string errorDefinitionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorDefinition {
            get {
                return this.errorDefinitionField;
            }
            set {
                this.errorDefinitionField = value;
                this.RaisePropertyChanged("ErrorDefinition");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UPSCancelOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UPSOrderResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] barkodArrayPngField;
        
        private string shipmentNoField;
        
        private string linkForLabelPrintingField;
        
        private int errorCodeField;
        
        private string errorDefinitionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] BarkodArrayPng {
            get {
                return this.barkodArrayPngField;
            }
            set {
                this.barkodArrayPngField = value;
                this.RaisePropertyChanged("BarkodArrayPng");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ShipmentNo {
            get {
                return this.shipmentNoField;
            }
            set {
                this.shipmentNoField = value;
                this.RaisePropertyChanged("ShipmentNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LinkForLabelPrinting {
            get {
                return this.linkForLabelPrintingField;
            }
            set {
                this.linkForLabelPrintingField = value;
                this.RaisePropertyChanged("LinkForLabelPrinting");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ErrorDefinition {
            get {
                return this.errorDefinitionField;
            }
            set {
                this.errorDefinitionField = value;
                this.RaisePropertyChanged("ErrorDefinition");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UPSSendOrderRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string shipperAccountNumberField;
        
        private string shipperNameField;
        
        private string shipperContactNameField;
        
        private string shipperAddressField;
        
        private int shipperCityCodeField;
        
        private int shipperAreaCodeField;
        
        private string shipperPhoneNumberField;
        
        private string shipperEMailField;
        
        private string shipperExpenseCodeField;
        
        private string consigneeAccountNumberField;
        
        private string consigneeNameField;
        
        private string consigneeContactNameField;
        
        private string consigneeAddressField;
        
        private int consigneeCityCodeField;
        
        private int consigneeAreaCodeField;
        
        private string consigneePhoneNumberField;
        
        private string consigneeEMailField;
        
        private string consigneeExpenseCodeField;
        
        private int serviceLevelField;
        
        private int paymentTypeField;
        
        private string packageTypeField;
        
        private int numberOfPackagesField;
        
        private string customerReferanceField;
        
        private string customerInvoiceNumberField;
        
        private string descriptionOfGoodsField;
        
        private string deliveryNotificationEmailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ShipperAccountNumber {
            get {
                return this.shipperAccountNumberField;
            }
            set {
                this.shipperAccountNumberField = value;
                this.RaisePropertyChanged("ShipperAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ShipperName {
            get {
                return this.shipperNameField;
            }
            set {
                this.shipperNameField = value;
                this.RaisePropertyChanged("ShipperName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ShipperContactName {
            get {
                return this.shipperContactNameField;
            }
            set {
                this.shipperContactNameField = value;
                this.RaisePropertyChanged("ShipperContactName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ShipperAddress {
            get {
                return this.shipperAddressField;
            }
            set {
                this.shipperAddressField = value;
                this.RaisePropertyChanged("ShipperAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ShipperCityCode {
            get {
                return this.shipperCityCodeField;
            }
            set {
                this.shipperCityCodeField = value;
                this.RaisePropertyChanged("ShipperCityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ShipperAreaCode {
            get {
                return this.shipperAreaCodeField;
            }
            set {
                this.shipperAreaCodeField = value;
                this.RaisePropertyChanged("ShipperAreaCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ShipperPhoneNumber {
            get {
                return this.shipperPhoneNumberField;
            }
            set {
                this.shipperPhoneNumberField = value;
                this.RaisePropertyChanged("ShipperPhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ShipperEMail {
            get {
                return this.shipperEMailField;
            }
            set {
                this.shipperEMailField = value;
                this.RaisePropertyChanged("ShipperEMail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ShipperExpenseCode {
            get {
                return this.shipperExpenseCodeField;
            }
            set {
                this.shipperExpenseCodeField = value;
                this.RaisePropertyChanged("ShipperExpenseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ConsigneeAccountNumber {
            get {
                return this.consigneeAccountNumberField;
            }
            set {
                this.consigneeAccountNumberField = value;
                this.RaisePropertyChanged("ConsigneeAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ConsigneeName {
            get {
                return this.consigneeNameField;
            }
            set {
                this.consigneeNameField = value;
                this.RaisePropertyChanged("ConsigneeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ConsigneeContactName {
            get {
                return this.consigneeContactNameField;
            }
            set {
                this.consigneeContactNameField = value;
                this.RaisePropertyChanged("ConsigneeContactName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ConsigneeAddress {
            get {
                return this.consigneeAddressField;
            }
            set {
                this.consigneeAddressField = value;
                this.RaisePropertyChanged("ConsigneeAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int ConsigneeCityCode {
            get {
                return this.consigneeCityCodeField;
            }
            set {
                this.consigneeCityCodeField = value;
                this.RaisePropertyChanged("ConsigneeCityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int ConsigneeAreaCode {
            get {
                return this.consigneeAreaCodeField;
            }
            set {
                this.consigneeAreaCodeField = value;
                this.RaisePropertyChanged("ConsigneeAreaCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ConsigneePhoneNumber {
            get {
                return this.consigneePhoneNumberField;
            }
            set {
                this.consigneePhoneNumberField = value;
                this.RaisePropertyChanged("ConsigneePhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ConsigneeEMail {
            get {
                return this.consigneeEMailField;
            }
            set {
                this.consigneeEMailField = value;
                this.RaisePropertyChanged("ConsigneeEMail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string ConsigneeExpenseCode {
            get {
                return this.consigneeExpenseCodeField;
            }
            set {
                this.consigneeExpenseCodeField = value;
                this.RaisePropertyChanged("ConsigneeExpenseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int ServiceLevel {
            get {
                return this.serviceLevelField;
            }
            set {
                this.serviceLevelField = value;
                this.RaisePropertyChanged("ServiceLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int PaymentType {
            get {
                return this.paymentTypeField;
            }
            set {
                this.paymentTypeField = value;
                this.RaisePropertyChanged("PaymentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string PackageType {
            get {
                return this.packageTypeField;
            }
            set {
                this.packageTypeField = value;
                this.RaisePropertyChanged("PackageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int NumberOfPackages {
            get {
                return this.numberOfPackagesField;
            }
            set {
                this.numberOfPackagesField = value;
                this.RaisePropertyChanged("NumberOfPackages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string CustomerReferance {
            get {
                return this.customerReferanceField;
            }
            set {
                this.customerReferanceField = value;
                this.RaisePropertyChanged("CustomerReferance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string CustomerInvoiceNumber {
            get {
                return this.customerInvoiceNumberField;
            }
            set {
                this.customerInvoiceNumberField = value;
                this.RaisePropertyChanged("CustomerInvoiceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string DescriptionOfGoods {
            get {
                return this.descriptionOfGoodsField;
            }
            set {
                this.descriptionOfGoodsField = value;
                this.RaisePropertyChanged("DescriptionOfGoods");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string DeliveryNotificationEmail {
            get {
                return this.deliveryNotificationEmailField;
            }
            set {
                this.deliveryNotificationEmailField = value;
                this.RaisePropertyChanged("DeliveryNotificationEmail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AIFCargoWebServicesSoapChannel : ZwillingCevaWebService.AIFCargoService.AIFCargoWebServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AIFCargoWebServicesSoapClient : System.ServiceModel.ClientBase<ZwillingCevaWebService.AIFCargoService.AIFCargoWebServicesSoap>, ZwillingCevaWebService.AIFCargoService.AIFCargoWebServicesSoap {
        
        public AIFCargoWebServicesSoapClient() {
        }
        
        public AIFCargoWebServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AIFCargoWebServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AIFCargoWebServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AIFCargoWebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ZwillingCevaWebService.AIFCargoService.UPSOrderResponse[] SendOrderToUPS(ZwillingCevaWebService.AIFCargoService.UPSLogin login, ZwillingCevaWebService.AIFCargoService.UPSSendOrderRequest[] UpsData) {
            return base.Channel.SendOrderToUPS(login, UpsData);
        }
        
        public System.Threading.Tasks.Task<ZwillingCevaWebService.AIFCargoService.UPSOrderResponse[]> SendOrderToUPSAsync(ZwillingCevaWebService.AIFCargoService.UPSLogin login, ZwillingCevaWebService.AIFCargoService.UPSSendOrderRequest[] UpsData) {
            return base.Channel.SendOrderToUPSAsync(login, UpsData);
        }
        
        public ZwillingCevaWebService.AIFCargoService.UPSCancelOrderResponse CancelOrderToUPS(ZwillingCevaWebService.AIFCargoService.UPSLogin login, ZwillingCevaWebService.AIFCargoService.UPSCancelOrder cancelOrderData) {
            return base.Channel.CancelOrderToUPS(login, cancelOrderData);
        }
        
        public System.Threading.Tasks.Task<ZwillingCevaWebService.AIFCargoService.UPSCancelOrderResponse> CancelOrderToUPSAsync(ZwillingCevaWebService.AIFCargoService.UPSLogin login, ZwillingCevaWebService.AIFCargoService.UPSCancelOrder cancelOrderData) {
            return base.Channel.CancelOrderToUPSAsync(login, cancelOrderData);
        }
        
        public ZwillingCevaWebService.AIFCargoService.YKOrderResponse[] SendOrderToYK(ZwillingCevaWebService.AIFCargoService.YKLogin login, ZwillingCevaWebService.AIFCargoService.YKSendOrderRequest[] ykData) {
            return base.Channel.SendOrderToYK(login, ykData);
        }
        
        public System.Threading.Tasks.Task<ZwillingCevaWebService.AIFCargoService.YKOrderResponse[]> SendOrderToYKAsync(ZwillingCevaWebService.AIFCargoService.YKLogin login, ZwillingCevaWebService.AIFCargoService.YKSendOrderRequest[] ykData) {
            return base.Channel.SendOrderToYKAsync(login, ykData);
        }
        
        public ZwillingCevaWebService.AIFCargoService.YKCancelOrderResponse[] CancelOrderToYK(ZwillingCevaWebService.AIFCargoService.YKLogin login, ZwillingCevaWebService.AIFCargoService.YKCancelOrderRequest[] ykData) {
            return base.Channel.CancelOrderToYK(login, ykData);
        }
        
        public System.Threading.Tasks.Task<ZwillingCevaWebService.AIFCargoService.YKCancelOrderResponse[]> CancelOrderToYKAsync(ZwillingCevaWebService.AIFCargoService.YKLogin login, ZwillingCevaWebService.AIFCargoService.YKCancelOrderRequest[] ykData) {
            return base.Channel.CancelOrderToYKAsync(login, ykData);
        }
        
        public ZwillingCevaWebService.AIFCargoService.Crystal CreatePDF(string docEntry) {
            return base.Channel.CreatePDF(docEntry);
        }
        
        public System.Threading.Tasks.Task<ZwillingCevaWebService.AIFCargoService.Crystal> CreatePDFAsync(string docEntry) {
            return base.Channel.CreatePDFAsync(docEntry);
        }
    }
}
