//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ServiceTest.AIFCargoWebServices {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AIFCargoWebServicesSoap", Namespace="http://tempuri.org/")]
    public partial class AIFCargoWebServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendOrderToUPSOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelOrderToUPSOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendOrderToYKOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelOrderToYKOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreatePDFOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOrderToMNGOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AIFCargoWebServices() {
            this.Url = global::ServiceTest.Properties.Settings.Default.ServiceTest_AIFCargoWebServices_AIFCargoWebServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendOrderToUPSCompletedEventHandler SendOrderToUPSCompleted;
        
        /// <remarks/>
        public event CancelOrderToUPSCompletedEventHandler CancelOrderToUPSCompleted;
        
        /// <remarks/>
        public event SendOrderToYKCompletedEventHandler SendOrderToYKCompleted;
        
        /// <remarks/>
        public event CancelOrderToYKCompletedEventHandler CancelOrderToYKCompleted;
        
        /// <remarks/>
        public event CreatePDFCompletedEventHandler CreatePDFCompleted;
        
        /// <remarks/>
        public event CreateOrderToMNGCompletedEventHandler CreateOrderToMNGCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendOrderToUPS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UPSOrderResponse[] SendOrderToUPS(UPSLogin login, UPSSendOrderRequest[] UpsData) {
            object[] results = this.Invoke("SendOrderToUPS", new object[] {
                        login,
                        UpsData});
            return ((UPSOrderResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void SendOrderToUPSAsync(UPSLogin login, UPSSendOrderRequest[] UpsData) {
            this.SendOrderToUPSAsync(login, UpsData, null);
        }
        
        /// <remarks/>
        public void SendOrderToUPSAsync(UPSLogin login, UPSSendOrderRequest[] UpsData, object userState) {
            if ((this.SendOrderToUPSOperationCompleted == null)) {
                this.SendOrderToUPSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendOrderToUPSOperationCompleted);
            }
            this.InvokeAsync("SendOrderToUPS", new object[] {
                        login,
                        UpsData}, this.SendOrderToUPSOperationCompleted, userState);
        }
        
        private void OnSendOrderToUPSOperationCompleted(object arg) {
            if ((this.SendOrderToUPSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendOrderToUPSCompleted(this, new SendOrderToUPSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelOrderToUPS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UPSCancelOrderResponse CancelOrderToUPS(UPSLogin login, UPSCancelOrder cancelOrderData) {
            object[] results = this.Invoke("CancelOrderToUPS", new object[] {
                        login,
                        cancelOrderData});
            return ((UPSCancelOrderResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CancelOrderToUPSAsync(UPSLogin login, UPSCancelOrder cancelOrderData) {
            this.CancelOrderToUPSAsync(login, cancelOrderData, null);
        }
        
        /// <remarks/>
        public void CancelOrderToUPSAsync(UPSLogin login, UPSCancelOrder cancelOrderData, object userState) {
            if ((this.CancelOrderToUPSOperationCompleted == null)) {
                this.CancelOrderToUPSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelOrderToUPSOperationCompleted);
            }
            this.InvokeAsync("CancelOrderToUPS", new object[] {
                        login,
                        cancelOrderData}, this.CancelOrderToUPSOperationCompleted, userState);
        }
        
        private void OnCancelOrderToUPSOperationCompleted(object arg) {
            if ((this.CancelOrderToUPSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelOrderToUPSCompleted(this, new CancelOrderToUPSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendOrderToYK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public YKOrderResponse[] SendOrderToYK(YKLogin login, YKSendOrderRequest[] ykData) {
            object[] results = this.Invoke("SendOrderToYK", new object[] {
                        login,
                        ykData});
            return ((YKOrderResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void SendOrderToYKAsync(YKLogin login, YKSendOrderRequest[] ykData) {
            this.SendOrderToYKAsync(login, ykData, null);
        }
        
        /// <remarks/>
        public void SendOrderToYKAsync(YKLogin login, YKSendOrderRequest[] ykData, object userState) {
            if ((this.SendOrderToYKOperationCompleted == null)) {
                this.SendOrderToYKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendOrderToYKOperationCompleted);
            }
            this.InvokeAsync("SendOrderToYK", new object[] {
                        login,
                        ykData}, this.SendOrderToYKOperationCompleted, userState);
        }
        
        private void OnSendOrderToYKOperationCompleted(object arg) {
            if ((this.SendOrderToYKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendOrderToYKCompleted(this, new SendOrderToYKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelOrderToYK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public YKCancelOrderResponse[] CancelOrderToYK(YKLogin login, YKCancelOrderRequest[] ykData) {
            object[] results = this.Invoke("CancelOrderToYK", new object[] {
                        login,
                        ykData});
            return ((YKCancelOrderResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void CancelOrderToYKAsync(YKLogin login, YKCancelOrderRequest[] ykData) {
            this.CancelOrderToYKAsync(login, ykData, null);
        }
        
        /// <remarks/>
        public void CancelOrderToYKAsync(YKLogin login, YKCancelOrderRequest[] ykData, object userState) {
            if ((this.CancelOrderToYKOperationCompleted == null)) {
                this.CancelOrderToYKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelOrderToYKOperationCompleted);
            }
            this.InvokeAsync("CancelOrderToYK", new object[] {
                        login,
                        ykData}, this.CancelOrderToYKOperationCompleted, userState);
        }
        
        private void OnCancelOrderToYKOperationCompleted(object arg) {
            if ((this.CancelOrderToYKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelOrderToYKCompleted(this, new CancelOrderToYKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreatePDF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Crystal CreatePDF(string docEntry) {
            object[] results = this.Invoke("CreatePDF", new object[] {
                        docEntry});
            return ((Crystal)(results[0]));
        }
        
        /// <remarks/>
        public void CreatePDFAsync(string docEntry) {
            this.CreatePDFAsync(docEntry, null);
        }
        
        /// <remarks/>
        public void CreatePDFAsync(string docEntry, object userState) {
            if ((this.CreatePDFOperationCompleted == null)) {
                this.CreatePDFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreatePDFOperationCompleted);
            }
            this.InvokeAsync("CreatePDF", new object[] {
                        docEntry}, this.CreatePDFOperationCompleted, userState);
        }
        
        private void OnCreatePDFOperationCompleted(object arg) {
            if ((this.CreatePDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreatePDFCompleted(this, new CreatePDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateOrderToMNG", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MNGCreateOrderResponse[] CreateOrderToMNG(MNGTokenRequest mngTokenRequest, MNGCreateOrderRequest[] mngCreateOrderRequest) {
            object[] results = this.Invoke("CreateOrderToMNG", new object[] {
                        mngTokenRequest,
                        mngCreateOrderRequest});
            return ((MNGCreateOrderResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateOrderToMNGAsync(MNGTokenRequest mngTokenRequest, MNGCreateOrderRequest[] mngCreateOrderRequest) {
            this.CreateOrderToMNGAsync(mngTokenRequest, mngCreateOrderRequest, null);
        }
        
        /// <remarks/>
        public void CreateOrderToMNGAsync(MNGTokenRequest mngTokenRequest, MNGCreateOrderRequest[] mngCreateOrderRequest, object userState) {
            if ((this.CreateOrderToMNGOperationCompleted == null)) {
                this.CreateOrderToMNGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOrderToMNGOperationCompleted);
            }
            this.InvokeAsync("CreateOrderToMNG", new object[] {
                        mngTokenRequest,
                        mngCreateOrderRequest}, this.CreateOrderToMNGOperationCompleted, userState);
        }
        
        private void OnCreateOrderToMNGOperationCompleted(object arg) {
            if ((this.CreateOrderToMNGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateOrderToMNGCompleted(this, new CreateOrderToMNGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UPSLogin {
        
        private string musteriKoduField;
        
        private string kullaniciKoduField;
        
        private string sifreField;
        
        /// <remarks/>
        public string MusteriKodu {
            get {
                return this.musteriKoduField;
            }
            set {
                this.musteriKoduField = value;
            }
        }
        
        /// <remarks/>
        public string KullaniciKodu {
            get {
                return this.kullaniciKoduField;
            }
            set {
                this.kullaniciKoduField = value;
            }
        }
        
        /// <remarks/>
        public string Sifre {
            get {
                return this.sifreField;
            }
            set {
                this.sifreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Error {
        
        private string codeField;
        
        private string messageField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MNGCreateOrderResponse {
        
        private string orderInvoiceIdField;
        
        private string orderInvoiceDetailIdField;
        
        private string shipperBranchCodeField;
        
        private Error[] errorsField;
        
        /// <remarks/>
        public string orderInvoiceId {
            get {
                return this.orderInvoiceIdField;
            }
            set {
                this.orderInvoiceIdField = value;
            }
        }
        
        /// <remarks/>
        public string orderInvoiceDetailId {
            get {
                return this.orderInvoiceDetailIdField;
            }
            set {
                this.orderInvoiceDetailIdField = value;
            }
        }
        
        /// <remarks/>
        public string shipperBranchCode {
            get {
                return this.shipperBranchCodeField;
            }
            set {
                this.shipperBranchCodeField = value;
            }
        }
        
        /// <remarks/>
        public Error[] errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Recipient {
        
        private int customerIdField;
        
        private string refCustomerIdField;
        
        private int cityCodeField;
        
        private string cityNameField;
        
        private string districtNameField;
        
        private int districtCodeField;
        
        private string addressField;
        
        private string bussinessPhoneNumberField;
        
        private string emailField;
        
        private string taxOfficeField;
        
        private string taxNumberField;
        
        private string fullNameField;
        
        private string homePhoneNumberField;
        
        private string mobilePhoneNumberField;
        
        /// <remarks/>
        public int customerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        public string refCustomerId {
            get {
                return this.refCustomerIdField;
            }
            set {
                this.refCustomerIdField = value;
            }
        }
        
        /// <remarks/>
        public int cityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
            }
        }
        
        /// <remarks/>
        public string cityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        public string districtName {
            get {
                return this.districtNameField;
            }
            set {
                this.districtNameField = value;
            }
        }
        
        /// <remarks/>
        public int districtCode {
            get {
                return this.districtCodeField;
            }
            set {
                this.districtCodeField = value;
            }
        }
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string bussinessPhoneNumber {
            get {
                return this.bussinessPhoneNumberField;
            }
            set {
                this.bussinessPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string taxOffice {
            get {
                return this.taxOfficeField;
            }
            set {
                this.taxOfficeField = value;
            }
        }
        
        /// <remarks/>
        public string taxNumber {
            get {
                return this.taxNumberField;
            }
            set {
                this.taxNumberField = value;
            }
        }
        
        /// <remarks/>
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public string homePhoneNumber {
            get {
                return this.homePhoneNumberField;
            }
            set {
                this.homePhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string mobilePhoneNumber {
            get {
                return this.mobilePhoneNumberField;
            }
            set {
                this.mobilePhoneNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderPieceList {
        
        private string barcodeField;
        
        private int desiField;
        
        private int kgField;
        
        private string contentField;
        
        /// <remarks/>
        public string barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        public int desi {
            get {
                return this.desiField;
            }
            set {
                this.desiField = value;
            }
        }
        
        /// <remarks/>
        public int kg {
            get {
                return this.kgField;
            }
            set {
                this.kgField = value;
            }
        }
        
        /// <remarks/>
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Order {
        
        private string referenceIdField;
        
        private string barcodeField;
        
        private string billOfLandingIdField;
        
        private int isCODField;
        
        private int codAmountField;
        
        private int shipmentServiceTypeField;
        
        private int packagingTypeField;
        
        private string contentField;
        
        private int smsPreference1Field;
        
        private int smsPreference2Field;
        
        private int smsPreference3Field;
        
        private int paymentTypeField;
        
        private int deliveryTypeField;
        
        private string descriptionField;
        
        private string marketPlaceShortCodeField;
        
        private string marketPlaceSaleCodeField;
        
        private string pudoIdField;
        
        /// <remarks/>
        public string referenceId {
            get {
                return this.referenceIdField;
            }
            set {
                this.referenceIdField = value;
            }
        }
        
        /// <remarks/>
        public string barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        public string billOfLandingId {
            get {
                return this.billOfLandingIdField;
            }
            set {
                this.billOfLandingIdField = value;
            }
        }
        
        /// <remarks/>
        public int isCOD {
            get {
                return this.isCODField;
            }
            set {
                this.isCODField = value;
            }
        }
        
        /// <remarks/>
        public int codAmount {
            get {
                return this.codAmountField;
            }
            set {
                this.codAmountField = value;
            }
        }
        
        /// <remarks/>
        public int shipmentServiceType {
            get {
                return this.shipmentServiceTypeField;
            }
            set {
                this.shipmentServiceTypeField = value;
            }
        }
        
        /// <remarks/>
        public int packagingType {
            get {
                return this.packagingTypeField;
            }
            set {
                this.packagingTypeField = value;
            }
        }
        
        /// <remarks/>
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public int smsPreference1 {
            get {
                return this.smsPreference1Field;
            }
            set {
                this.smsPreference1Field = value;
            }
        }
        
        /// <remarks/>
        public int smsPreference2 {
            get {
                return this.smsPreference2Field;
            }
            set {
                this.smsPreference2Field = value;
            }
        }
        
        /// <remarks/>
        public int smsPreference3 {
            get {
                return this.smsPreference3Field;
            }
            set {
                this.smsPreference3Field = value;
            }
        }
        
        /// <remarks/>
        public int paymentType {
            get {
                return this.paymentTypeField;
            }
            set {
                this.paymentTypeField = value;
            }
        }
        
        /// <remarks/>
        public int deliveryType {
            get {
                return this.deliveryTypeField;
            }
            set {
                this.deliveryTypeField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string marketPlaceShortCode {
            get {
                return this.marketPlaceShortCodeField;
            }
            set {
                this.marketPlaceShortCodeField = value;
            }
        }
        
        /// <remarks/>
        public string marketPlaceSaleCode {
            get {
                return this.marketPlaceSaleCodeField;
            }
            set {
                this.marketPlaceSaleCodeField = value;
            }
        }
        
        /// <remarks/>
        public string pudoId {
            get {
                return this.pudoIdField;
            }
            set {
                this.pudoIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MNGCreateOrderRequest {
        
        private Order orderField;
        
        private OrderPieceList[] orderPieceListField;
        
        private Recipient recipientField;
        
        /// <remarks/>
        public Order order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        public OrderPieceList[] orderPieceList {
            get {
                return this.orderPieceListField;
            }
            set {
                this.orderPieceListField = value;
            }
        }
        
        /// <remarks/>
        public Recipient recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MNGTokenRequest {
        
        private string customerNumberField;
        
        private string passwordField;
        
        private string identityTypeField;
        
        /// <remarks/>
        public string customerNumber {
            get {
                return this.customerNumberField;
            }
            set {
                this.customerNumberField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string identityType {
            get {
                return this.identityTypeField;
            }
            set {
                this.identityTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Crystal {
        
        private int valField;
        
        private string descField;
        
        private string pathField;
        
        /// <remarks/>
        public int Val {
            get {
                return this.valField;
            }
            set {
                this.valField = value;
            }
        }
        
        /// <remarks/>
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelDetails {
        
        private string cargoKeyField;
        
        private int errCodeField;
        
        private string errDescField;
        
        private string invoiceKeyField;
        
        private long docIdField;
        
        private long operationCodeField;
        
        private string operationStatusField;
        
        private string operationMessageField;
        
        /// <remarks/>
        public string CargoKey {
            get {
                return this.cargoKeyField;
            }
            set {
                this.cargoKeyField = value;
            }
        }
        
        /// <remarks/>
        public int ErrCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
            }
        }
        
        /// <remarks/>
        public string invoiceKey {
            get {
                return this.invoiceKeyField;
            }
            set {
                this.invoiceKeyField = value;
            }
        }
        
        /// <remarks/>
        public long docId {
            get {
                return this.docIdField;
            }
            set {
                this.docIdField = value;
            }
        }
        
        /// <remarks/>
        public long operationCode {
            get {
                return this.operationCodeField;
            }
            set {
                this.operationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string operationStatus {
            get {
                return this.operationStatusField;
            }
            set {
                this.operationStatusField = value;
            }
        }
        
        /// <remarks/>
        public string operationMessage {
            get {
                return this.operationMessageField;
            }
            set {
                this.operationMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class YKCancelOrderResponse {
        
        private string outResultField;
        
        private string outFlagField;
        
        private long jobIdField;
        
        private long countField;
        
        private string errCodeField;
        
        private CancelDetails detailsField;
        
        /// <remarks/>
        public string OutResult {
            get {
                return this.outResultField;
            }
            set {
                this.outResultField = value;
            }
        }
        
        /// <remarks/>
        public string OutFlag {
            get {
                return this.outFlagField;
            }
            set {
                this.outFlagField = value;
            }
        }
        
        /// <remarks/>
        public long jobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
            }
        }
        
        /// <remarks/>
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public string errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        public CancelDetails Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class YKCancelOrderRequest {
        
        private string cargoKeyField;
        
        /// <remarks/>
        public string CargoKey {
            get {
                return this.cargoKeyField;
            }
            set {
                this.cargoKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Details {
        
        private string cargoKeyField;
        
        private int errCodeField;
        
        private string errDescField;
        
        /// <remarks/>
        public string CargoKey {
            get {
                return this.cargoKeyField;
            }
            set {
                this.cargoKeyField = value;
            }
        }
        
        /// <remarks/>
        public int ErrCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class YKOrderResponse {
        
        private string outResultField;
        
        private string outFlagField;
        
        private long jobIdField;
        
        private long countField;
        
        private string errCodeField;
        
        private Details detailsField;
        
        /// <remarks/>
        public string OutResult {
            get {
                return this.outResultField;
            }
            set {
                this.outResultField = value;
            }
        }
        
        /// <remarks/>
        public string OutFlag {
            get {
                return this.outFlagField;
            }
            set {
                this.outFlagField = value;
            }
        }
        
        /// <remarks/>
        public long jobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
            }
        }
        
        /// <remarks/>
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public string errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        public Details Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class YKSendOrderRequest {
        
        private string cargoKeyField;
        
        private string invoiceKeyField;
        
        private string receiverCustNameField;
        
        private string receiverAddressField;
        
        private string cityNameField;
        
        private string townNameField;
        
        private string receiverPhone1Field;
        
        private string receiverPhone2Field;
        
        private string receiverPhone3Field;
        
        private string emailAddressField;
        
        private long taxOfficeIdField;
        
        private string taxNumberField;
        
        private string taxOfficeNameField;
        
        private double desiField;
        
        private bool desiFieldSpecified;
        
        private double kgField;
        
        private bool kgFieldSpecified;
        
        private int cargoCountField;
        
        private string waybillNoField;
        
        private string specialField1Field;
        
        private string specialField2Field;
        
        private string specialField3Field;
        
        private double ttInvoiceAmountField;
        
        private bool ttInvoiceAmountFieldSpecified;
        
        private long ttDocumentIdField;
        
        private string ttCollectionTypeField;
        
        private string ttDocumentSaveTypeField;
        
        private long dcSelectedCreditField;
        
        private long dcCreditRuleField;
        
        private string descriptionField;
        
        private string orgGeoCodeField;
        
        private string privilegeOrderField;
        
        private string custProdIdField;
        
        private string orgReceiverCustIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cargoKey {
            get {
                return this.cargoKeyField;
            }
            set {
                this.cargoKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string invoiceKey {
            get {
                return this.invoiceKeyField;
            }
            set {
                this.invoiceKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string receiverCustName {
            get {
                return this.receiverCustNameField;
            }
            set {
                this.receiverCustNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string receiverAddress {
            get {
                return this.receiverAddressField;
            }
            set {
                this.receiverAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string townName {
            get {
                return this.townNameField;
            }
            set {
                this.townNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string receiverPhone1 {
            get {
                return this.receiverPhone1Field;
            }
            set {
                this.receiverPhone1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string receiverPhone2 {
            get {
                return this.receiverPhone2Field;
            }
            set {
                this.receiverPhone2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string receiverPhone3 {
            get {
                return this.receiverPhone3Field;
            }
            set {
                this.receiverPhone3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long taxOfficeId {
            get {
                return this.taxOfficeIdField;
            }
            set {
                this.taxOfficeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string taxNumber {
            get {
                return this.taxNumberField;
            }
            set {
                this.taxNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string taxOfficeName {
            get {
                return this.taxOfficeNameField;
            }
            set {
                this.taxOfficeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double desi {
            get {
                return this.desiField;
            }
            set {
                this.desiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool desiSpecified {
            get {
                return this.desiFieldSpecified;
            }
            set {
                this.desiFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double kg {
            get {
                return this.kgField;
            }
            set {
                this.kgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool kgSpecified {
            get {
                return this.kgFieldSpecified;
            }
            set {
                this.kgFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cargoCount {
            get {
                return this.cargoCountField;
            }
            set {
                this.cargoCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string waybillNo {
            get {
                return this.waybillNoField;
            }
            set {
                this.waybillNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string specialField1 {
            get {
                return this.specialField1Field;
            }
            set {
                this.specialField1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string specialField2 {
            get {
                return this.specialField2Field;
            }
            set {
                this.specialField2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string specialField3 {
            get {
                return this.specialField3Field;
            }
            set {
                this.specialField3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double ttInvoiceAmount {
            get {
                return this.ttInvoiceAmountField;
            }
            set {
                this.ttInvoiceAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ttInvoiceAmountSpecified {
            get {
                return this.ttInvoiceAmountFieldSpecified;
            }
            set {
                this.ttInvoiceAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long ttDocumentId {
            get {
                return this.ttDocumentIdField;
            }
            set {
                this.ttDocumentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ttCollectionType {
            get {
                return this.ttCollectionTypeField;
            }
            set {
                this.ttCollectionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ttDocumentSaveType {
            get {
                return this.ttDocumentSaveTypeField;
            }
            set {
                this.ttDocumentSaveTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long dcSelectedCredit {
            get {
                return this.dcSelectedCreditField;
            }
            set {
                this.dcSelectedCreditField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long dcCreditRule {
            get {
                return this.dcCreditRuleField;
            }
            set {
                this.dcCreditRuleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orgGeoCode {
            get {
                return this.orgGeoCodeField;
            }
            set {
                this.orgGeoCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string privilegeOrder {
            get {
                return this.privilegeOrderField;
            }
            set {
                this.privilegeOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string custProdId {
            get {
                return this.custProdIdField;
            }
            set {
                this.custProdIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orgReceiverCustId {
            get {
                return this.orgReceiverCustIdField;
            }
            set {
                this.orgReceiverCustIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class YKLogin {
        
        private string userLanguageField;
        
        private string wsPasswordField;
        
        private string wsUserNameField;
        
        /// <remarks/>
        public string userLanguage {
            get {
                return this.userLanguageField;
            }
            set {
                this.userLanguageField = value;
            }
        }
        
        /// <remarks/>
        public string wsPassword {
            get {
                return this.wsPasswordField;
            }
            set {
                this.wsPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string wsUserName {
            get {
                return this.wsUserNameField;
            }
            set {
                this.wsUserNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UPSCancelOrderResponse {
        
        private int errorCodeField;
        
        private string errorDefinitionField;
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDefinition {
            get {
                return this.errorDefinitionField;
            }
            set {
                this.errorDefinitionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UPSCancelOrder {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UPSOrderResponse {
        
        private string[] barkodArrayPngField;
        
        private string shipmentNoField;
        
        private string linkForLabelPrintingField;
        
        private int errorCodeField;
        
        private string errorDefinitionField;
        
        /// <remarks/>
        public string[] BarkodArrayPng {
            get {
                return this.barkodArrayPngField;
            }
            set {
                this.barkodArrayPngField = value;
            }
        }
        
        /// <remarks/>
        public string ShipmentNo {
            get {
                return this.shipmentNoField;
            }
            set {
                this.shipmentNoField = value;
            }
        }
        
        /// <remarks/>
        public string LinkForLabelPrinting {
            get {
                return this.linkForLabelPrintingField;
            }
            set {
                this.linkForLabelPrintingField = value;
            }
        }
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDefinition {
            get {
                return this.errorDefinitionField;
            }
            set {
                this.errorDefinitionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UPSSendOrderRequest {
        
        private string shipperAccountNumberField;
        
        private string shipperNameField;
        
        private string shipperContactNameField;
        
        private string shipperAddressField;
        
        private int shipperCityCodeField;
        
        private int shipperAreaCodeField;
        
        private string shipperPhoneNumberField;
        
        private string shipperEMailField;
        
        private string shipperExpenseCodeField;
        
        private string consigneeAccountNumberField;
        
        private string consigneeNameField;
        
        private string consigneeContactNameField;
        
        private string consigneeAddressField;
        
        private int consigneeCityCodeField;
        
        private int consigneeAreaCodeField;
        
        private string consigneePhoneNumberField;
        
        private string consigneeEMailField;
        
        private string consigneeExpenseCodeField;
        
        private int serviceLevelField;
        
        private int paymentTypeField;
        
        private string packageTypeField;
        
        private int numberOfPackagesField;
        
        private string customerReferanceField;
        
        private string customerInvoiceNumberField;
        
        private string descriptionOfGoodsField;
        
        private string deliveryNotificationEmailField;
        
        /// <remarks/>
        public string ShipperAccountNumber {
            get {
                return this.shipperAccountNumberField;
            }
            set {
                this.shipperAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ShipperName {
            get {
                return this.shipperNameField;
            }
            set {
                this.shipperNameField = value;
            }
        }
        
        /// <remarks/>
        public string ShipperContactName {
            get {
                return this.shipperContactNameField;
            }
            set {
                this.shipperContactNameField = value;
            }
        }
        
        /// <remarks/>
        public string ShipperAddress {
            get {
                return this.shipperAddressField;
            }
            set {
                this.shipperAddressField = value;
            }
        }
        
        /// <remarks/>
        public int ShipperCityCode {
            get {
                return this.shipperCityCodeField;
            }
            set {
                this.shipperCityCodeField = value;
            }
        }
        
        /// <remarks/>
        public int ShipperAreaCode {
            get {
                return this.shipperAreaCodeField;
            }
            set {
                this.shipperAreaCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ShipperPhoneNumber {
            get {
                return this.shipperPhoneNumberField;
            }
            set {
                this.shipperPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ShipperEMail {
            get {
                return this.shipperEMailField;
            }
            set {
                this.shipperEMailField = value;
            }
        }
        
        /// <remarks/>
        public string ShipperExpenseCode {
            get {
                return this.shipperExpenseCodeField;
            }
            set {
                this.shipperExpenseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ConsigneeAccountNumber {
            get {
                return this.consigneeAccountNumberField;
            }
            set {
                this.consigneeAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ConsigneeName {
            get {
                return this.consigneeNameField;
            }
            set {
                this.consigneeNameField = value;
            }
        }
        
        /// <remarks/>
        public string ConsigneeContactName {
            get {
                return this.consigneeContactNameField;
            }
            set {
                this.consigneeContactNameField = value;
            }
        }
        
        /// <remarks/>
        public string ConsigneeAddress {
            get {
                return this.consigneeAddressField;
            }
            set {
                this.consigneeAddressField = value;
            }
        }
        
        /// <remarks/>
        public int ConsigneeCityCode {
            get {
                return this.consigneeCityCodeField;
            }
            set {
                this.consigneeCityCodeField = value;
            }
        }
        
        /// <remarks/>
        public int ConsigneeAreaCode {
            get {
                return this.consigneeAreaCodeField;
            }
            set {
                this.consigneeAreaCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ConsigneePhoneNumber {
            get {
                return this.consigneePhoneNumberField;
            }
            set {
                this.consigneePhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ConsigneeEMail {
            get {
                return this.consigneeEMailField;
            }
            set {
                this.consigneeEMailField = value;
            }
        }
        
        /// <remarks/>
        public string ConsigneeExpenseCode {
            get {
                return this.consigneeExpenseCodeField;
            }
            set {
                this.consigneeExpenseCodeField = value;
            }
        }
        
        /// <remarks/>
        public int ServiceLevel {
            get {
                return this.serviceLevelField;
            }
            set {
                this.serviceLevelField = value;
            }
        }
        
        /// <remarks/>
        public int PaymentType {
            get {
                return this.paymentTypeField;
            }
            set {
                this.paymentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string PackageType {
            get {
                return this.packageTypeField;
            }
            set {
                this.packageTypeField = value;
            }
        }
        
        /// <remarks/>
        public int NumberOfPackages {
            get {
                return this.numberOfPackagesField;
            }
            set {
                this.numberOfPackagesField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerReferance {
            get {
                return this.customerReferanceField;
            }
            set {
                this.customerReferanceField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerInvoiceNumber {
            get {
                return this.customerInvoiceNumberField;
            }
            set {
                this.customerInvoiceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string DescriptionOfGoods {
            get {
                return this.descriptionOfGoodsField;
            }
            set {
                this.descriptionOfGoodsField = value;
            }
        }
        
        /// <remarks/>
        public string DeliveryNotificationEmail {
            get {
                return this.deliveryNotificationEmailField;
            }
            set {
                this.deliveryNotificationEmailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SendOrderToUPSCompletedEventHandler(object sender, SendOrderToUPSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendOrderToUPSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendOrderToUPSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UPSOrderResponse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UPSOrderResponse[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CancelOrderToUPSCompletedEventHandler(object sender, CancelOrderToUPSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelOrderToUPSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelOrderToUPSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UPSCancelOrderResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UPSCancelOrderResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SendOrderToYKCompletedEventHandler(object sender, SendOrderToYKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendOrderToYKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendOrderToYKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public YKOrderResponse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((YKOrderResponse[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CancelOrderToYKCompletedEventHandler(object sender, CancelOrderToYKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelOrderToYKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelOrderToYKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public YKCancelOrderResponse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((YKCancelOrderResponse[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CreatePDFCompletedEventHandler(object sender, CreatePDFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreatePDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreatePDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Crystal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Crystal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CreateOrderToMNGCompletedEventHandler(object sender, CreateOrderToMNGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateOrderToMNGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateOrderToMNGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MNGCreateOrderResponse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MNGCreateOrderResponse[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591